### ISSUE TITLE
Create a release checklist

### ISSUE THREAD

**Issue by pvginkel** [TQLApp/TQL#200]
This needs to include at least:

- [ ] All NuGet packages have been updated.
- [ ] All dotnet tools have been updated.
- [ ] WiX was updated to the latest version.
